import { Instrutor } from '@/types'

const rawMock: any[] = [
  {
    id: '1',
    nome: 'Carlos Eduardo Silva',
    cpf: '123.456.789-00',
    data_nascimento: '1985-03-15',
    email: 'carlos@email.com',
    telefone: '(11) 99876-5432',
    foto_url: 'https://i.pravatar.cc/150?img=1',
    registro_senatran: 'SEN-2024-001234',
    categorias: ['B'],
    anos_experiencia: 8,
    alunos_formados: 342,
    plano: 'profissional',
    documentos: [
      { id: 'doc1', instrutor_id: '1', tipo: 'certificado_senatran', nome_arquivo: 'certificado_senatran.pdf', url: '/docs/cert1.pdf', uploaded_at: '2024-01-15' },
      { id: 'doc2', instrutor_id: '1', tipo: 'comprovante_residencia', nome_arquivo: 'comprovante_residencia.pdf', url: '/docs/comp1.pdf', uploaded_at: '2024-01-15' },
      { id: 'doc3', instrutor_id: '1', tipo: 'cnh', nome_arquivo: 'cnh.pdf', url: '/docs/cnh1.pdf', uploaded_at: '2024-01-15' },
    ],
    descricao: 'Instrutor credenciado com mais de 8 anos de experiência. Especialista em primeira habilitação, com método paciente e didático. Atendo na zona sul de São Paulo com veículo próprio equipado com duplo comando.',
    preco_hora: 85,
    aceita_veiculo_candidato: true,
    genero: 'masculino',
    status: 'aprovado',
    slug: 'carlos-eduardo-silva-sp',
    created_at: '2024-01-15',
    localizacao: {
      id: 'l1',
      instrutor_id: '1',
      cep: '04567-000',
      cidade: 'São Paulo',
      estado: 'SP',
      bairro: 'Moema',
      lat: -23.5989,
      lng: -46.6658,
      raio_km: 15,
    },
    disponibilidades: [
      { id: 'd1', instrutor_id: '1', dia_semana: 1, turno: 'manha' },
      { id: 'd2', instrutor_id: '1', dia_semana: 1, turno: 'tarde' },
      { id: 'd3', instrutor_id: '1', dia_semana: 2, turno: 'manha' },
      { id: 'd4', instrutor_id: '1', dia_semana: 3, turno: 'manha' },
      { id: 'd5', instrutor_id: '1', dia_semana: 3, turno: 'tarde' },
      { id: 'd6', instrutor_id: '1', dia_semana: 4, turno: 'tarde' },
      { id: 'd7', instrutor_id: '1', dia_semana: 5, turno: 'manha' },
    ],
    veiculos: [
      { id: 'v1', instrutor_id: '1', marca: 'Chevrolet', modelo: 'Onix Plus', ano: 2024, cambio: 'manual', foto_url: '' },
      { id: 'v2', instrutor_id: '1', marca: 'Hyundai', modelo: 'HB20', ano: 2023, cambio: 'automatico', foto_url: '' },
    ],
    avaliacoes: [
      { id: 'a1', instrutor_id: '1', nome_aluno: 'Maria L.', nota: 5, comentario: 'Excelente instrutor! Muito paciente e didático. Passei de primeira graças ao Carlos.', resposta_instrutor: 'Obrigado, Maria! Foi um prazer te ajudar nessa jornada. Sucesso na estrada! 🚗', created_at: '2024-03-10' },
      { id: 'a2', instrutor_id: '1', nome_aluno: 'Pedro S.', nota: 5, comentario: 'Profissional demais. Explica tudo com calma e me deixou bem seguro para a prova.', created_at: '2024-02-28' },
      { id: 'a3', instrutor_id: '1', nome_aluno: 'Ana C.', nota: 4, comentario: 'Muito bom instrutor, pontual e dedicado. Recomendo!', created_at: '2024-01-20' },
    ],
  },
  {
    id: '2',
    nome: 'Fernanda Oliveira Santos',
    cpf: '234.567.890-11',
    data_nascimento: '1982-07-22',
    email: 'fernanda@email.com',
    telefone: '(21) 98765-4321',
    foto_url: 'https://i.pravatar.cc/150?img=5',
    registro_senatran: 'SEN-2024-002345',
    categorias: ['A', 'B'],
    anos_experiencia: 12,
    alunos_formados: 578,
    plano: 'premium',
    documentos: [
      { id: 'doc4', instrutor_id: '2', tipo: 'certificado_senatran', nome_arquivo: 'cert_fernanda.pdf', url: '/docs/cert2.pdf', uploaded_at: '2024-01-10' },
      { id: 'doc5', instrutor_id: '2', tipo: 'comprovante_residencia', nome_arquivo: 'comp_fernanda.pdf', url: '/docs/comp2.pdf', uploaded_at: '2024-01-10' },
    ],
    descricao: 'Instrutora com 12 anos de experiência, especialista em categorias A e B. Método focado em segurança e confiança ao volante. Atendo em toda zona oeste do Rio de Janeiro.',
    preco_hora: 95,
    aceita_veiculo_candidato: false,
    genero: 'feminino',
    status: 'aprovado',
    slug: 'fernanda-oliveira-santos-rj',
    created_at: '2024-01-10',
    localizacao: {
      id: 'l2',
      instrutor_id: '2',
      cep: '22640-100',
      cidade: 'Rio de Janeiro',
      estado: 'RJ',
      bairro: 'Barra da Tijuca',
      lat: -23.0003,
      lng: -43.3658,
      raio_km: 20,
    },
    disponibilidades: [
      { id: 'd8', instrutor_id: '2', dia_semana: 1, turno: 'tarde' },
      { id: 'd9', instrutor_id: '2', dia_semana: 2, turno: 'manha' },
      { id: 'd10', instrutor_id: '2', dia_semana: 2, turno: 'tarde' },
      { id: 'd11', instrutor_id: '2', dia_semana: 3, turno: 'manha' },
      { id: 'd12', instrutor_id: '2', dia_semana: 4, turno: 'manha' },
      { id: 'd13', instrutor_id: '2', dia_semana: 4, turno: 'tarde' },
      { id: 'd14', instrutor_id: '2', dia_semana: 5, turno: 'tarde' },
      { id: 'd15', instrutor_id: '2', dia_semana: 5, turno: 'noite' },
    ],
    veiculos: [
      { id: 'v3', instrutor_id: '2', marca: 'Toyota', modelo: 'Yaris', ano: 2024, cambio: 'automatico', foto_url: '' },
      { id: 'v4', instrutor_id: '2', marca: 'Honda', modelo: 'CG 160', ano: 2023, cambio: 'manual', foto_url: '' },
    ],
    avaliacoes: [
      { id: 'a4', instrutor_id: '2', nome_aluno: 'Lucas M.', nota: 5, comentario: 'A Fernanda é incrível! Muito profissional e me ajudou a superar o medo de dirigir.', resposta_instrutor: 'Lucas, fico feliz demais! Você se dedicou muito, o mérito é todo seu!', created_at: '2024-04-05' },
      { id: 'a5', instrutor_id: '2', nome_aluno: 'Julia R.', nota: 5, comentario: 'Melhor instrutora do Rio! Atenciosa, pontual e com didática perfeita.', created_at: '2024-03-15' },
      { id: 'a6', instrutor_id: '2', nome_aluno: 'Rafael T.', nota: 4, comentario: 'Ótima experiência. Aprendi bastante sobre moto e carro com ela.', created_at: '2024-02-20' },
    ],
  },
  {
    id: '3',
    nome: 'Roberto Almeida Costa',
    cpf: '345.678.901-22',
    data_nascimento: '1990-11-05',
    email: 'roberto@email.com',
    telefone: '(31) 97654-3210',
    foto_url: 'https://i.pravatar.cc/150?img=3',
    registro_senatran: 'SEN-2024-003456',
    categorias: ['B'],
    anos_experiencia: 5,
    alunos_formados: 189,
    plano: 'basico',
    documentos: [
      { id: 'doc6', instrutor_id: '3', tipo: 'certificado_senatran', nome_arquivo: 'cert_roberto.pdf', url: '/docs/cert3.pdf', uploaded_at: '2024-02-01' },
      { id: 'doc7', instrutor_id: '3', tipo: 'comprovante_residencia', nome_arquivo: 'comp_roberto.pdf', url: '/docs/comp3.pdf', uploaded_at: '2024-02-01' },
    ],
    descricao: 'Instrutor jovem e dinâmico, formado pelo Senatran. Foco em aulas práticas objetivas e eficientes. Uso técnicas modernas de ensino para você aprender rápido e com segurança.',
    preco_hora: 70,
    aceita_veiculo_candidato: true,
    genero: 'masculino',
    status: 'aprovado',
    slug: 'roberto-almeida-costa-bh',
    created_at: '2024-02-01',
    localizacao: {
      id: 'l3',
      instrutor_id: '3',
      cep: '30130-000',
      cidade: 'Belo Horizonte',
      estado: 'MG',
      bairro: 'Savassi',
      lat: -19.9332,
      lng: -43.9381,
      raio_km: 12,
    },
    disponibilidades: [
      { id: 'd16', instrutor_id: '3', dia_semana: 1, turno: 'manha' },
      { id: 'd17', instrutor_id: '3', dia_semana: 1, turno: 'tarde' },
      { id: 'd18', instrutor_id: '3', dia_semana: 1, turno: 'noite' },
      { id: 'd19', instrutor_id: '3', dia_semana: 3, turno: 'manha' },
      { id: 'd20', instrutor_id: '3', dia_semana: 3, turno: 'tarde' },
      { id: 'd21', instrutor_id: '3', dia_semana: 5, turno: 'manha' },
      { id: 'd22', instrutor_id: '3', dia_semana: 5, turno: 'tarde' },
    ],
    veiculos: [
      { id: 'v5', instrutor_id: '3', marca: 'Volkswagen', modelo: 'Polo', ano: 2023, cambio: 'manual', foto_url: '' },
    ],
    avaliacoes: [
      { id: 'a7', instrutor_id: '3', nome_aluno: 'Camila F.', nota: 5, comentario: 'Roberto é muito gente boa e explica super bem. Recomendo demais!', created_at: '2024-03-20' },
      { id: 'a8', instrutor_id: '3', nome_aluno: 'Diego N.', nota: 4, comentario: 'Bom instrutor, aulas práticas e diretas ao ponto.', created_at: '2024-03-05' },
      { id: 'a9', instrutor_id: '3', nome_aluno: 'Isabela G.', nota: 5, comentario: 'Aprovei de primeira! O Roberto tem uma paciência incrível.', resposta_instrutor: 'Parabéns, Isa! Sabia que você ia conseguir! 🎉', created_at: '2024-02-15' },
    ],
  },
  {
    id: '4',
    nome: 'Patrícia Mendes Lima',
    cpf: '456.789.012-33',
    data_nascimento: '1978-04-18',
    email: 'patricia@email.com',
    telefone: '(41) 96543-2109',
    foto_url: 'https://i.pravatar.cc/150?img=9',
    registro_senatran: 'SEN-2024-004567',
    categorias: ['A', 'B'],
    anos_experiencia: 15,
    alunos_formados: 823,
    plano: 'premium',
    documentos: [
      { id: 'doc8', instrutor_id: '4', tipo: 'certificado_senatran', nome_arquivo: 'cert_patricia.pdf', url: '/docs/cert4.pdf', uploaded_at: '2024-01-05' },
      { id: 'doc9', instrutor_id: '4', tipo: 'comprovante_residencia', nome_arquivo: 'comp_patricia.pdf', url: '/docs/comp4.pdf', uploaded_at: '2024-01-05' },
    ],
    descricao: 'Com 15 anos de atuação, sou uma das instrutoras mais experientes de Curitiba. Método próprio focado em confiança e autonomia do aluno. Formei mais de 800 motoristas com alto índice de aprovação.',
    preco_hora: 110,
    aceita_veiculo_candidato: true,
    genero: 'feminino',
    status: 'aprovado',
    slug: 'patricia-mendes-lima-cwb',
    created_at: '2024-01-05',
    localizacao: {
      id: 'l4',
      instrutor_id: '4',
      cep: '80240-000',
      cidade: 'Curitiba',
      estado: 'PR',
      bairro: 'Batel',
      lat: -25.4411,
      lng: -49.2920,
      raio_km: 18,
    },
    disponibilidades: [
      { id: 'd23', instrutor_id: '4', dia_semana: 1, turno: 'manha' },
      { id: 'd24', instrutor_id: '4', dia_semana: 2, turno: 'manha' },
      { id: 'd25', instrutor_id: '4', dia_semana: 2, turno: 'tarde' },
      { id: 'd26', instrutor_id: '4', dia_semana: 3, turno: 'tarde' },
      { id: 'd27', instrutor_id: '4', dia_semana: 4, turno: 'manha' },
      { id: 'd28', instrutor_id: '4', dia_semana: 4, turno: 'tarde' },
    ],
    veiculos: [
      { id: 'v6', instrutor_id: '4', marca: 'Fiat', modelo: 'Argo', ano: 2024, cambio: 'manual', foto_url: '' },
      { id: 'v7', instrutor_id: '4', marca: 'Fiat', modelo: 'Argo', ano: 2024, cambio: 'automatico', foto_url: '' },
      { id: 'v8', instrutor_id: '4', marca: 'Honda', modelo: 'CG 160', ano: 2024, cambio: 'manual', foto_url: '' },
    ],
    avaliacoes: [
      { id: 'a10', instrutor_id: '4', nome_aluno: 'Thiago B.', nota: 5, comentario: 'A Patrícia é simplesmente a melhor! Profissional, pontual e muito didática.', resposta_instrutor: 'Obrigada, Thiago! Sucesso na sua jornada como motorista!', created_at: '2024-04-10' },
      { id: 'a11', instrutor_id: '4', nome_aluno: 'Amanda K.', nota: 5, comentario: 'Fiz aulas de moto e carro com ela. Excelente nos dois. Super recomendo!', created_at: '2024-03-22' },
      { id: 'a12', instrutor_id: '4', nome_aluno: 'Marcos V.', nota: 4, comentario: 'Muito boa, mas o preço é um pouco acima da média. Vale pela qualidade.', created_at: '2024-02-18' },
    ],
  },
  {
    id: '5',
    nome: 'André Rodrigues Souza',
    cpf: '567.890.123-44',
    data_nascimento: '1988-09-12',
    email: 'andre@email.com',
    telefone: '(51) 95432-1098',
    foto_url: 'https://i.pravatar.cc/150?img=4',
    registro_senatran: 'SEN-2024-005678',
    categorias: ['B'],
    anos_experiencia: 6,
    alunos_formados: 267,
    plano: 'basico',
    documentos: [
      { id: 'doc10', instrutor_id: '5', tipo: 'certificado_senatran', nome_arquivo: 'cert_andre.pdf', url: '/docs/cert5.pdf', uploaded_at: '2024-01-20' },
    ],
    descricao: 'Instrutor credenciado em Porto Alegre. Aulas descontraídas mas focadas em resultado. Meu objetivo é que você passe na prova com segurança e confiança de verdade.',
    preco_hora: 75,
    aceita_veiculo_candidato: false,
    genero: 'masculino',
    status: 'aprovado',
    slug: 'andre-rodrigues-souza-poa',
    created_at: '2024-01-20',
    localizacao: {
      id: 'l5',
      instrutor_id: '5',
      cep: '90040-000',
      cidade: 'Porto Alegre',
      estado: 'RS',
      bairro: 'Moinhos de Vento',
      lat: -30.0261,
      lng: -51.2010,
      raio_km: 10,
    },
    disponibilidades: [
      { id: 'd29', instrutor_id: '5', dia_semana: 1, turno: 'tarde' },
      { id: 'd30', instrutor_id: '5', dia_semana: 2, turno: 'manha' },
      { id: 'd31', instrutor_id: '5', dia_semana: 2, turno: 'tarde' },
      { id: 'd32', instrutor_id: '5', dia_semana: 3, turno: 'noite' },
      { id: 'd33', instrutor_id: '5', dia_semana: 4, turno: 'manha' },
      { id: 'd34', instrutor_id: '5', dia_semana: 5, turno: 'manha' },
      { id: 'd35', instrutor_id: '5', dia_semana: 5, turno: 'tarde' },
    ],
    veiculos: [
      { id: 'v9', instrutor_id: '5', marca: 'Renault', modelo: 'Kwid', ano: 2024, cambio: 'manual', foto_url: '' },
    ],
    avaliacoes: [
      { id: 'a13', instrutor_id: '5', nome_aluno: 'Bruna S.', nota: 4, comentario: 'André é muito tranquilo e passa segurança. Gostei bastante das aulas.', created_at: '2024-04-01' },
      { id: 'a14', instrutor_id: '5', nome_aluno: 'Felipe M.', nota: 5, comentario: 'Cara sensacional! Aprendi muito rápido com o método dele.', resposta_instrutor: 'Valeu, Felipe! Bora pra estrada! 🚗💨', created_at: '2024-03-10' },
      { id: 'a15', instrutor_id: '5', nome_aluno: 'Carolina D.', nota: 4, comentario: 'Bom instrutor, atencioso e com boa didática. Recomendo.', created_at: '2024-02-25' },
    ],
  },
  {
    id: '6',
    nome: 'Luciana Barbosa Reis',
    cpf: '678.901.234-55',
    data_nascimento: '1984-01-30',
    email: 'luciana@email.com',
    telefone: '(71) 94321-0987',
    foto_url: 'https://i.pravatar.cc/150?img=10',
    registro_senatran: 'SEN-2024-006789',
    categorias: ['A', 'B'],
    anos_experiencia: 10,
    alunos_formados: 456,
    plano: 'basico',
    documentos: [
      { id: 'doc11', instrutor_id: '6', tipo: 'certificado_senatran', nome_arquivo: 'cert_luciana.pdf', url: '/docs/cert6.pdf', uploaded_at: '2024-01-25' },
      { id: 'doc12', instrutor_id: '6', tipo: 'comprovante_residencia', nome_arquivo: 'comp_luciana.pdf', url: '/docs/comp6.pdf', uploaded_at: '2024-01-25' },
    ],
    descricao: 'Instrutora experiente em Salvador. Trabalho com foco especial em alunos com medo de dirigir. Ambiente acolhedor e sem pressão. Venha aprender no seu ritmo!',
    preco_hora: 80,
    aceita_veiculo_candidato: true,
    genero: 'feminino',
    status: 'aprovado',
    slug: 'luciana-barbosa-reis-ssa',
    created_at: '2024-01-25',
    localizacao: {
      id: 'l6',
      instrutor_id: '6',
      cep: '40140-000',
      cidade: 'Salvador',
      estado: 'BA',
      bairro: 'Pituba',
      lat: -12.9871,
      lng: -38.4568,
      raio_km: 15,
    },
    disponibilidades: [
      { id: 'd36', instrutor_id: '6', dia_semana: 1, turno: 'manha' },
      { id: 'd37', instrutor_id: '6', dia_semana: 1, turno: 'tarde' },
      { id: 'd38', instrutor_id: '6', dia_semana: 2, turno: 'tarde' },
      { id: 'd39', instrutor_id: '6', dia_semana: 3, turno: 'manha' },
      { id: 'd40', instrutor_id: '6', dia_semana: 4, turno: 'manha' },
      { id: 'd41', instrutor_id: '6', dia_semana: 4, turno: 'tarde' },
      { id: 'd42', instrutor_id: '6', dia_semana: 5, turno: 'noite' },
    ],
    veiculos: [
      { id: 'v10', instrutor_id: '6', marca: 'Chevrolet', modelo: 'Tracker', ano: 2023, cambio: 'automatico', foto_url: '' },
      { id: 'v11', instrutor_id: '6', marca: 'Yamaha', modelo: 'Factor 150', ano: 2024, cambio: 'manual', foto_url: '' },
    ],
    avaliacoes: [
      { id: 'a16', instrutor_id: '6', nome_aluno: 'Priscila A.', nota: 5, comentario: 'Luciana é maravilhosa! Eu morria de medo e ela me ajudou a superar. Hoje dirijo tranquilamente.', resposta_instrutor: 'Priscila, que orgulho de você! Sabia que ia conseguir! ❤️', created_at: '2024-04-08' },
      { id: 'a17', instrutor_id: '6', nome_aluno: 'Gustavo H.', nota: 4, comentario: 'Profissional muito competente. Aulas bem organizadas.', created_at: '2024-03-18' },
      { id: 'a18', instrutor_id: '6', nome_aluno: 'Daniela P.', nota: 5, comentario: 'Fiz categoria A e B com a Lu. Impecável nos dois. Super recomendo!', created_at: '2024-02-28' },
    ],
  },
  {
    id: '7',
    nome: 'Marcos Henrique Pereira',
    cpf: '789.012.345-66',
    data_nascimento: '1995-06-08',
    email: 'marcos@email.com',
    telefone: '(85) 93210-9876',
    foto_url: 'https://i.pravatar.cc/150?img=7',
    registro_senatran: 'SEN-2024-007890',
    categorias: ['B'],
    anos_experiencia: 3,
    alunos_formados: 98,
    plano: 'basico',
    documentos: [
      { id: 'doc13', instrutor_id: '7', tipo: 'certificado_senatran', nome_arquivo: 'cert_marcos.pdf', url: '/docs/cert7.pdf', uploaded_at: '2024-02-10' },
    ],
    descricao: 'Instrutor novo no mercado mas com muita dedicação. Preço justo e aulas bem preparadas. Se você busca economia sem abrir mão da qualidade, sou sua melhor opção em Fortaleza!',
    preco_hora: 60,
    aceita_veiculo_candidato: true,
    genero: 'masculino',
    status: 'aprovado',
    slug: 'marcos-henrique-pereira-for',
    created_at: '2024-02-10',
    localizacao: {
      id: 'l7',
      instrutor_id: '7',
      cep: '60165-000',
      cidade: 'Fortaleza',
      estado: 'CE',
      bairro: 'Meireles',
      lat: -3.7261,
      lng: -38.5008,
      raio_km: 10,
    },
    disponibilidades: [
      { id: 'd43', instrutor_id: '7', dia_semana: 1, turno: 'manha' },
      { id: 'd44', instrutor_id: '7', dia_semana: 1, turno: 'tarde' },
      { id: 'd45', instrutor_id: '7', dia_semana: 1, turno: 'noite' },
      { id: 'd46', instrutor_id: '7', dia_semana: 2, turno: 'manha' },
      { id: 'd47', instrutor_id: '7', dia_semana: 2, turno: 'tarde' },
      { id: 'd48', instrutor_id: '7', dia_semana: 3, turno: 'manha' },
      { id: 'd49', instrutor_id: '7', dia_semana: 4, turno: 'tarde' },
      { id: 'd50', instrutor_id: '7', dia_semana: 5, turno: 'manha' },
      { id: 'd51', instrutor_id: '7', dia_semana: 5, turno: 'tarde' },
      { id: 'd52', instrutor_id: '7', dia_semana: 5, turno: 'noite' },
    ],
    veiculos: [
      { id: 'v12', instrutor_id: '7', marca: 'Fiat', modelo: 'Mobi', ano: 2023, cambio: 'manual', foto_url: '' },
    ],
    avaliacoes: [
      { id: 'a19', instrutor_id: '7', nome_aluno: 'Renata L.', nota: 5, comentario: 'Marcos é ótimo! Preço justo e aulas muito boas. Passei de primeira!', created_at: '2024-04-02' },
      { id: 'a20', instrutor_id: '7', nome_aluno: 'Vinícius C.', nota: 4, comentario: 'Bom custo-benefício. O Marcos se esforça bastante.', created_at: '2024-03-12' },
      { id: 'a21', instrutor_id: '7', nome_aluno: 'Tatiane M.', nota: 4, comentario: 'Gostei das aulas, ele é bem paciente e o preço é honesto.', resposta_instrutor: 'Obrigado, Tati! Fico feliz que tenha gostado!', created_at: '2024-02-20' },
    ],
  },
  {
    id: '8',
    nome: 'Ricardo Nascimento Borges',
    cpf: '890.123.456-77',
    data_nascimento: '1975-12-20',
    email: 'ricardo@email.com',
    telefone: '(61) 92109-8765',
    foto_url: 'https://i.pravatar.cc/150?img=8',
    registro_senatran: 'SEN-2024-008901',
    categorias: ['A', 'B'],
    anos_experiencia: 20,
    alunos_formados: 1250,
    plano: 'premium',
    documentos: [
      { id: 'doc14', instrutor_id: '8', tipo: 'certificado_senatran', nome_arquivo: 'cert_ricardo.pdf', url: '/docs/cert8.pdf', uploaded_at: '2024-01-01' },
      { id: 'doc15', instrutor_id: '8', tipo: 'comprovante_residencia', nome_arquivo: 'comp_ricardo.pdf', url: '/docs/comp8.pdf', uploaded_at: '2024-01-01' },
      { id: 'doc16', instrutor_id: '8', tipo: 'cnh', nome_arquivo: 'cnh_ricardo.pdf', url: '/docs/cnh8.pdf', uploaded_at: '2024-01-01' },
    ],
    descricao: 'Veterano com 20 anos de experiência e mais de 1.200 alunos formados. Referência em Brasília para habilitação A e B. Método estruturado com alto índice de aprovação na primeira tentativa.',
    preco_hora: 150,
    aceita_veiculo_candidato: false,
    genero: 'masculino',
    status: 'aprovado',
    slug: 'ricardo-nascimento-borges-bsb',
    created_at: '2024-01-01',
    localizacao: {
      id: 'l8',
      instrutor_id: '8',
      cep: '70070-000',
      cidade: 'Brasília',
      estado: 'DF',
      bairro: 'Asa Sul',
      lat: -15.7975,
      lng: -47.8919,
      raio_km: 25,
    },
    disponibilidades: [
      { id: 'd53', instrutor_id: '8', dia_semana: 1, turno: 'manha' },
      { id: 'd54', instrutor_id: '8', dia_semana: 1, turno: 'tarde' },
      { id: 'd55', instrutor_id: '8', dia_semana: 2, turno: 'manha' },
      { id: 'd56', instrutor_id: '8', dia_semana: 3, turno: 'manha' },
      { id: 'd57', instrutor_id: '8', dia_semana: 3, turno: 'tarde' },
      { id: 'd58', instrutor_id: '8', dia_semana: 4, turno: 'manha' },
    ],
    veiculos: [
      { id: 'v13', instrutor_id: '8', marca: 'Toyota', modelo: 'Corolla Cross', ano: 2024, cambio: 'automatico', foto_url: '' },
      { id: 'v14', instrutor_id: '8', marca: 'Volkswagen', modelo: 'Virtus', ano: 2024, cambio: 'manual', foto_url: '' },
      { id: 'v15', instrutor_id: '8', marca: 'BMW', modelo: 'G 310 GS', ano: 2024, cambio: 'manual', foto_url: '' },
    ],
    avaliacoes: [
      { id: 'a22', instrutor_id: '8', nome_aluno: 'Eduardo F.', nota: 5, comentario: 'O Ricardo é lenda! 20 anos de experiência fazem diferença. Aula impecável.', resposta_instrutor: 'Obrigado, Eduardo! A experiência vem da paixão pelo que faço!', created_at: '2024-04-12' },
      { id: 'a23', instrutor_id: '8', nome_aluno: 'Larissa W.', nota: 5, comentario: 'Vale cada centavo. O melhor instrutor de Brasília sem dúvida.', created_at: '2024-03-25' },
      { id: 'a24', instrutor_id: '8', nome_aluno: 'Gabriel R.', nota: 5, comentario: 'Fiz A e B com ele. Estrutura das aulas é perfeita. Aprovei os dois de primeira!', created_at: '2024-03-01' },
    ],
  },
  {
    id: '9',
    nome: 'João Victor Mendes',
    cpf: '901.234.567-88',
    data_nascimento: '1992-05-14',
    email: 'joao@email.com',
    telefone: '(62) 91234-5678',
    foto_url: 'https://i.pravatar.cc/150?img=11',
    registro_senatran: 'SEN-2025-009012',
    categorias: ['B'],
    anos_experiencia: 2,
    alunos_formados: 45,
    plano: 'basico',
    documentos: [
      { id: 'doc17', instrutor_id: '9', tipo: 'certificado_senatran', nome_arquivo: 'cert_joao.pdf', url: '/docs/cert9.pdf', uploaded_at: '2025-03-20' },
      { id: 'doc18', instrutor_id: '9', tipo: 'comprovante_residencia', nome_arquivo: 'comp_joao.pdf', url: '/docs/comp9.pdf', uploaded_at: '2025-03-20' },
    ],
    descricao: 'Instrutor recém-credenciado em Goiânia. Aulas com método moderno e didático.',
    preco_hora: 65,
    aceita_veiculo_candidato: true,
    genero: 'masculino',
    status: 'em_analise',
    slug: 'joao-victor-mendes-gyn',
    created_at: '2025-03-20',
    localizacao: {
      id: 'l9',
      instrutor_id: '9',
      cep: '74015-000',
      cidade: 'Goiânia',
      estado: 'GO',
      bairro: 'Setor Bueno',
      lat: -16.7042,
      lng: -49.2551,
      raio_km: 12,
    },
    disponibilidades: [
      { id: 'd59', instrutor_id: '9', dia_semana: 1, turno: 'manha' },
      { id: 'd60', instrutor_id: '9', dia_semana: 3, turno: 'tarde' },
      { id: 'd61', instrutor_id: '9', dia_semana: 5, turno: 'manha' },
    ],
    veiculos: [
      { id: 'v16', instrutor_id: '9', marca: 'Hyundai', modelo: 'HB20', ano: 2023, cambio: 'manual', foto_url: '' },
    ],
    avaliacoes: [],
  },
  {
    id: '10',
    nome: 'Aline Souza Ferreira',
    cpf: '012.345.678-99',
    data_nascimento: '1993-08-25',
    email: 'aline@email.com',
    telefone: '(48) 90987-6543',
    foto_url: 'https://i.pravatar.cc/150?img=12',
    registro_senatran: 'SEN-2025-010123',
    categorias: ['A', 'B'],
    anos_experiencia: 4,
    alunos_formados: 120,
    plano: 'basico',
    documentos: [
      { id: 'doc19', instrutor_id: '10', tipo: 'certificado_senatran', nome_arquivo: 'cert_aline.pdf', url: '/docs/cert10.pdf', uploaded_at: '2025-03-15' },
    ],
    descricao: 'Instrutora em Florianópolis com foco em alunas mulheres. Ambiente acolhedor e sem pressão.',
    preco_hora: 75,
    aceita_veiculo_candidato: false,
    genero: 'feminino',
    status: 'recusado',
    motivo_recusa: 'Documentação do comprovante de residência não foi enviada. Por favor, reenvie com comprovante atualizado dos últimos 3 meses.',
    slug: 'aline-souza-ferreira-fln',
    created_at: '2025-03-15',
    localizacao: {
      id: 'l10',
      instrutor_id: '10',
      cep: '88015-000',
      cidade: 'Florianópolis',
      estado: 'SC',
      bairro: 'Centro',
      lat: -27.5954,
      lng: -48.5480,
      raio_km: 10,
    },
    disponibilidades: [
      { id: 'd62', instrutor_id: '10', dia_semana: 2, turno: 'manha' },
      { id: 'd63', instrutor_id: '10', dia_semana: 4, turno: 'tarde' },
    ],
    veiculos: [
      { id: 'v17', instrutor_id: '10', marca: 'Toyota', modelo: 'Etios', ano: 2022, cambio: 'manual', foto_url: '' },
    ],
    avaliacoes: [],
  },
]

export const mockInstrutores: Instrutor[] = rawMock as Instrutor[]

export function getInstrutorBySlug(slug: string): Instrutor | undefined {
  return mockInstrutores.find(i => i.slug === slug)
}

export function getInstrutoresAprovados(): Instrutor[] {
  return mockInstrutores.filter(i => i.status === 'aprovado')
}

export function getInstrutoresByCidade(cidade: string): Instrutor[] {
  const aprovados = getInstrutoresAprovados()
  if (!cidade) return aprovados
  return aprovados.filter(i =>
    i.localizacao.cidade.toLowerCase().includes(cidade.toLowerCase())
  )
}

export function getMediaAvaliacao(avaliacoes: { nota: number }[]): number {
  if (!avaliacoes.length) return 0
  return avaliacoes.reduce((acc, a) => acc + a.nota, 0) / avaliacoes.length
}
